### ISSUE TITLE
Different input ?

### ISSUE THREAD

**Issue by Roobyx** [pyko/random-name-picker#1]
Is there any way to input the data from a txt file (or any file) ?

**Comment by pyko** [comment]
Currently there isn't. The only input method is to enter them individually - sort of like people putting their names into a hat.

What is your use case for getting data input from a file?

**Comment by Roobyx** [comment]
Thx for the fast answer !

The case is that we have a system that inputs the name in excel file and when the times come, we want to input them and choose a winner. So far your way is the best we have found, but we cannot input the names (actually numbers) manually since they will be at least 1 thousand.

**Comment by pyko** [comment]
No worries!

Hm, I assume need that selection animation/effect? Otherwise you can always go for a simple random number generator like: http://www.random.org/

**Comment by Roobyx** [comment]
Yep, we do need AND like the animations. Out first try was with random.org, but It wont be nice to show it on a big screen :)

**Comment by pyko** [comment]
Good news... got distracted from what I was supposed to do, so have implemented basic input via a file :)

I've updated the README with the instructions - hopefully it's what you need :)

Two things to note:
1. A large number of entries can cause things to slow down - haven't optimised it to handle a big load (tested with ~2000 entries on my laptop and it's a bit slow to load, but works)
2. So that it doesn't take forever to pick a winner, I've added `MAX_LIST_LENGTH = 300` to limit the number of entries it'll cycle through. Increase/decrease this number depending on how long you want the process to take. Note, these 300 are picked randomly - so it is still fair

**Comment by Roobyx** [comment]
Thats Great !!! Thank you! This is a life saver ! I'll test it after work
